extract_research_topics:
  description: >
    Find the research topics from research proposals, 
    then using these research topics to search the relevant references papers 
    in literature databases and online. The research proposal in markdown:

    {research_proposal}
    
  expected_output: >
    the list of research topics
  agent: PhD_candidate

paper_review:
  description: >
    read papers in a local subdirectory and reference to research proposal: {research_proposal}.
    Make a academic review based them.
  
  expected_output: >
    a academic review paper in markdown formart, save the review paper in the local file

  output_file: "review.md"
  agent: PhD_candidate

